CREATE DATABASE ESCOLA;

CREATE TABLE ALUNOS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    RA VARCHAR(255) NOT NULL
)

INSERT INTO ALUNOS (NOME, RA) VALUES ('JOCEMAR','12356')